modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="reaktor"
version="1.0.0"
displayName="Reaktor Library"
description="A library for computing atomic reactions"
entryPoint="maven.hexagon.reaktorjava.Reaktor"
